application: uq-artag
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data
- url: /aframes
  static_dir: aframes
- url: /three.js
  static_dir: three.js
- url: /test
  static_dir: test
- url: /webvr-polyfill
  static_dir: webvr-polyfill